# Generated by Django 2.0.1 on 2019-04-19 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medtechapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Remedies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('disease', models.CharField(max_length=200)),
                ('remedie_pic', models.CharField(max_length=1000)),
            ],
        ),
    ]
