# Generated by Django 2.0.1 on 2019-04-19 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medtechapp', '0002_remedies'),
    ]

    operations = [
        migrations.RenameField(
            model_name='remedies',
            old_name='name',
            new_name='ingredients',
        ),
    ]
