# Generated by Django 2.0.1 on 2019-04-19 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medtechapp', '0004_auto_20190419_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='remedies',
            name='sol1',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='remedies',
            name='sol2',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='remedies',
            name='sol3',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
