# Generated by Django 2.0.1 on 2019-04-19 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medtechapp', '0005_auto_20190419_0956'),
    ]

    operations = [
        migrations.RenameField(
            model_name='remedies',
            old_name='remedie_pic',
            new_name='pic1',
        ),
        migrations.AddField(
            model_name='remedies',
            name='pic2',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='remedies',
            name='pic3',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
