# Generated by Django 2.0.1 on 2019-04-19 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medtechapp', '0006_auto_20190419_1009'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Remedies',
            new_name='Solutions',
        ),
    ]
