# Generated by Django 2.0.1 on 2019-04-25 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medtechapp', '0007_auto_20190419_1029'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewEntryTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(default='', max_length=100)),
                ('lname', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=100)),
                ('contact', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
