# Generated by Django 2.0.1 on 2019-04-25 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medtechapp', '0008_auto_20190425_1948'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='', max_length=100)),
                ('gender', models.CharField(default='', max_length=100)),
                ('birth', models.CharField(default='', max_length=100)),
                ('address', models.CharField(default='', max_length=100)),
                ('mobile_no', models.CharField(default='', max_length=100)),
                ('pincode', models.CharField(default='', max_length=100)),
                ('organs', models.CharField(default='', max_length=100)),
                ('blood_group', models.CharField(default='', max_length=100)),
                ('myfile', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='newentrytable',
            name='hname',
            field=models.CharField(default='', max_length=100),
        ),
    ]
