# Generated by Django 2.0.1 on 2019-04-26 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medtechapp', '0009_auto_20190425_2356'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospitalname', models.CharField(max_length=100)),
                ('token', models.IntegerField()),
            ],
        ),
    ]
